package com.moha.demo.entity;

import java.util.Date;

public class AsAccountdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.id
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.userId
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.detailType
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    private Integer detailType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.detailTypeName
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    private String detailTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.money
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.accountMoney
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    private Double accountMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.memo
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_accountdetail.detaildateTime
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    private Date detaildateTime;

    private AsUser user;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.id
     *
     * @return the value of as_accountdetail.id
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.id
     *
     * @param id the value for as_accountdetail.id
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.userId
     *
     * @return the value of as_accountdetail.userId
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.userId
     *
     * @param userId the value for as_accountdetail.userId
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.detailType
     *
     * @return the value of as_accountdetail.detailType
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public Integer getDetailType() {
        return detailType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.detailType
     *
     * @param detailType the value for as_accountdetail.detailType
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public void setDetailType(Integer detailType) {
        this.detailType = detailType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.detailTypeName
     *
     * @return the value of as_accountdetail.detailTypeName
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public String getDetailTypeName() {
        return detailTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.detailTypeName
     *
     * @param detailTypeName the value for as_accountdetail.detailTypeName
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public void setDetailTypeName(String detailTypeName) {
        this.detailTypeName = detailTypeName == null ? null : detailTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.money
     *
     * @return the value of as_accountdetail.money
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.money
     *
     * @param money the value for as_accountdetail.money
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.accountMoney
     *
     * @return the value of as_accountdetail.accountMoney
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public Double getAccountMoney() {
        return accountMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.accountMoney
     *
     * @param accountMoney the value for as_accountdetail.accountMoney
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public void setAccountMoney(Double accountMoney) {
        this.accountMoney = accountMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.memo
     *
     * @return the value of as_accountdetail.memo
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.memo
     *
     * @param memo the value for as_accountdetail.memo
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_accountdetail.detaildateTime
     *
     * @return the value of as_accountdetail.detaildateTime
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public Date getDetaildateTime() {
        return detaildateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_accountdetail.detaildateTime
     *
     * @param detaildateTime the value for as_accountdetail.detaildateTime
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    public void setDetaildateTime(Date detaildateTime) {
        this.detaildateTime = detaildateTime;
    }

    public AsUser getUser() {
        return user;
    }

    public void setUser(AsUser user) {
        this.user = user;
    }
}