package com.moha.demo.entity;

public class AsAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_account.id
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_account.userId
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_account.money
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_account.moneyBak
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    private Double moneyBak;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_account.id
     *
     * @return the value of as_account.id
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_account.id
     *
     * @param id the value for as_account.id
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_account.userId
     *
     * @return the value of as_account.userId
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_account.userId
     *
     * @param userId the value for as_account.userId
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_account.money
     *
     * @return the value of as_account.money
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_account.money
     *
     * @param money the value for as_account.money
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_account.moneyBak
     *
     * @return the value of as_account.moneyBak
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    public Double getMoneyBak() {
        return moneyBak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_account.moneyBak
     *
     * @param moneyBak the value for as_account.moneyBak
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    public void setMoneyBak(Double moneyBak) {
        this.moneyBak = moneyBak;
    }
}