package com.moha.demo.entity;

public class AsContacts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.id
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.customId
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    private Integer customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.contactName
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.contactTel
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    private String contactTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.contactFax
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    private String contactFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.contactEmail
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    private String contactEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_contacts.contactRole
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    private String contactRole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.id
     *
     * @return the value of as_contacts.id
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.id
     *
     * @param id the value for as_contacts.id
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.customId
     *
     * @return the value of as_contacts.customId
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public Integer getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.customId
     *
     * @param customId the value for as_contacts.customId
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public void setCustomId(Integer customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.contactName
     *
     * @return the value of as_contacts.contactName
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.contactName
     *
     * @param contactName the value for as_contacts.contactName
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.contactTel
     *
     * @return the value of as_contacts.contactTel
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.contactTel
     *
     * @param contactTel the value for as_contacts.contactTel
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel == null ? null : contactTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.contactFax
     *
     * @return the value of as_contacts.contactFax
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public String getContactFax() {
        return contactFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.contactFax
     *
     * @param contactFax the value for as_contacts.contactFax
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public void setContactFax(String contactFax) {
        this.contactFax = contactFax == null ? null : contactFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.contactEmail
     *
     * @return the value of as_contacts.contactEmail
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.contactEmail
     *
     * @param contactEmail the value for as_contacts.contactEmail
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail == null ? null : contactEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_contacts.contactRole
     *
     * @return the value of as_contacts.contactRole
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public String getContactRole() {
        return contactRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_contacts.contactRole
     *
     * @param contactRole the value for as_contacts.contactRole
     *
     * @mbggenerated Mon Feb 05 14:40:44 CST 2018
     */
    public void setContactRole(String contactRole) {
        this.contactRole = contactRole == null ? null : contactRole.trim();
    }
}