package com.moha.demo.entity;

import java.util.Date;
import java.util.List;

public class AsCustoms {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.id
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.agentId
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private Integer agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.agentName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String agentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.customName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String customName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.customType
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private Integer customType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.customTypeName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String customTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.siteUrl
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String siteUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.customStatus
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private Integer customStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.bossName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String bossName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.cardType
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private Integer cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.cardTypeName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String cardTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.cardNum
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.companyTel
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String companyTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.companyFax
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String companyFax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.regdateTime
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private Date regdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.country
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.province
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.city
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.area
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.companyAddress
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.memo
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.agentCode
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String agentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_customs.email
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    private String email;

    private HatProvince pro;
    private HatCity cit;
    private HatArea are;

    public HatProvince getPro() {
        return pro;
    }

    public void setPro(HatProvince pro) {
        this.pro = pro;
    }

    public HatCity getCit() {
        return cit;
    }

    public void setCit(HatCity cit) {
        this.cit = cit;
    }

    public HatArea getAre() {
        return are;
    }

    public void setAre(HatArea are) {
        this.are = are;
    }

    public List<AsContacts> getContacts() {
        return contacts;
    }

    public void setContacts(List<AsContacts> contacts) {
        this.contacts = contacts;
    }

    private List<AsContacts> contacts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.id
     *
     * @return the value of as_customs.id
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.id
     *
     * @param id the value for as_customs.id
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.agentId
     *
     * @return the value of as_customs.agentId
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.agentId
     *
     * @param agentId the value for as_customs.agentId
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.agentName
     *
     * @return the value of as_customs.agentName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.agentName
     *
     * @param agentName the value for as_customs.agentName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setAgentName(String agentName) {
        this.agentName = agentName == null ? null : agentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.customName
     *
     * @return the value of as_customs.customName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.customName
     *
     * @param customName the value for as_customs.customName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setCustomName(String customName) {
        this.customName = customName == null ? null : customName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.customType
     *
     * @return the value of as_customs.customType
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public Integer getCustomType() {
        return customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.customType
     *
     * @param customType the value for as_customs.customType
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setCustomType(Integer customType) {
        this.customType = customType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.customTypeName
     *
     * @return the value of as_customs.customTypeName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getCustomTypeName() {
        return customTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.customTypeName
     *
     * @param customTypeName the value for as_customs.customTypeName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setCustomTypeName(String customTypeName) {
        this.customTypeName = customTypeName == null ? null : customTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.siteUrl
     *
     * @return the value of as_customs.siteUrl
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getSiteUrl() {
        return siteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.siteUrl
     *
     * @param siteUrl the value for as_customs.siteUrl
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setSiteUrl(String siteUrl) {
        this.siteUrl = siteUrl == null ? null : siteUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.customStatus
     *
     * @return the value of as_customs.customStatus
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public Integer getCustomStatus() {
        return customStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.customStatus
     *
     * @param customStatus the value for as_customs.customStatus
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setCustomStatus(Integer customStatus) {
        this.customStatus = customStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.bossName
     *
     * @return the value of as_customs.bossName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getBossName() {
        return bossName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.bossName
     *
     * @param bossName the value for as_customs.bossName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setBossName(String bossName) {
        this.bossName = bossName == null ? null : bossName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.cardType
     *
     * @return the value of as_customs.cardType
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public Integer getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.cardType
     *
     * @param cardType the value for as_customs.cardType
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.cardTypeName
     *
     * @return the value of as_customs.cardTypeName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getCardTypeName() {
        return cardTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.cardTypeName
     *
     * @param cardTypeName the value for as_customs.cardTypeName
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setCardTypeName(String cardTypeName) {
        this.cardTypeName = cardTypeName == null ? null : cardTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.cardNum
     *
     * @return the value of as_customs.cardNum
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.cardNum
     *
     * @param cardNum the value for as_customs.cardNum
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum == null ? null : cardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.companyTel
     *
     * @return the value of as_customs.companyTel
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getCompanyTel() {
        return companyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.companyTel
     *
     * @param companyTel the value for as_customs.companyTel
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setCompanyTel(String companyTel) {
        this.companyTel = companyTel == null ? null : companyTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.companyFax
     *
     * @return the value of as_customs.companyFax
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getCompanyFax() {
        return companyFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.companyFax
     *
     * @param companyFax the value for as_customs.companyFax
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setCompanyFax(String companyFax) {
        this.companyFax = companyFax == null ? null : companyFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.regdateTime
     *
     * @return the value of as_customs.regdateTime
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public Date getRegdateTime() {
        return regdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.regdateTime
     *
     * @param regdateTime the value for as_customs.regdateTime
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setRegdateTime(Date regdateTime) {
        this.regdateTime = regdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.country
     *
     * @return the value of as_customs.country
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.country
     *
     * @param country the value for as_customs.country
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.province
     *
     * @return the value of as_customs.province
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.province
     *
     * @param province the value for as_customs.province
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.city
     *
     * @return the value of as_customs.city
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.city
     *
     * @param city the value for as_customs.city
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.area
     *
     * @return the value of as_customs.area
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.area
     *
     * @param area the value for as_customs.area
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.companyAddress
     *
     * @return the value of as_customs.companyAddress
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.companyAddress
     *
     * @param companyAddress the value for as_customs.companyAddress
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.memo
     *
     * @return the value of as_customs.memo
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.memo
     *
     * @param memo the value for as_customs.memo
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.agentCode
     *
     * @return the value of as_customs.agentCode
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getAgentCode() {
        return agentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.agentCode
     *
     * @param agentCode the value for as_customs.agentCode
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode == null ? null : agentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_customs.email
     *
     * @return the value of as_customs.email
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_customs.email
     *
     * @param email the value for as_customs.email
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}