package com.moha.demo.entity;

import java.util.Date;

public class AsKeywords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.id
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.keywords
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.agentId
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Integer agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.agentName
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private String agentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.customId
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Integer customId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.customName
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private String customName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.preRegFrozenMoney
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Double preRegFrozenMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.price
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.productType
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Integer productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.serviceYears
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Integer serviceYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.openApp
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Integer openApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.appUserName
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private String appUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.appPassword
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private String appPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.loginUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private String loginUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.iosDownloadUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private String iosDownloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.androidDownloadUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private String androidDownloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.codeIosUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private String codeIosUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.codeAndroidUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private String codeAndroidUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.preRegdatetime
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Date preRegdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.preRegPassdatetime
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Date preRegPassdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.regdatetime
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Date regdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.regPassdatetime
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Date regPassdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.isPass
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Integer isPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.checkStatus
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Integer checkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_keywords.isUse
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    private Integer isUse;

    private AsCustoms customs;
    private AsSystemconfig systemconfig;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.id
     *
     * @return the value of as_keywords.id
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.id
     *
     * @param id the value for as_keywords.id
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.keywords
     *
     * @return the value of as_keywords.keywords
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.keywords
     *
     * @param keywords the value for as_keywords.keywords
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.agentId
     *
     * @return the value of as_keywords.agentId
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.agentId
     *
     * @param agentId the value for as_keywords.agentId
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.agentName
     *
     * @return the value of as_keywords.agentName
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.agentName
     *
     * @param agentName the value for as_keywords.agentName
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setAgentName(String agentName) {
        this.agentName = agentName == null ? null : agentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.customId
     *
     * @return the value of as_keywords.customId
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Integer getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.customId
     *
     * @param customId the value for as_keywords.customId
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setCustomId(Integer customId) {
        this.customId = customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.customName
     *
     * @return the value of as_keywords.customName
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.customName
     *
     * @param customName the value for as_keywords.customName
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setCustomName(String customName) {
        this.customName = customName == null ? null : customName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.preRegFrozenMoney
     *
     * @return the value of as_keywords.preRegFrozenMoney
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Double getPreRegFrozenMoney() {
        return preRegFrozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.preRegFrozenMoney
     *
     * @param preRegFrozenMoney the value for as_keywords.preRegFrozenMoney
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setPreRegFrozenMoney(Double preRegFrozenMoney) {
        this.preRegFrozenMoney = preRegFrozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.price
     *
     * @return the value of as_keywords.price
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.price
     *
     * @param price the value for as_keywords.price
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.productType
     *
     * @return the value of as_keywords.productType
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.productType
     *
     * @param productType the value for as_keywords.productType
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.serviceYears
     *
     * @return the value of as_keywords.serviceYears
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Integer getServiceYears() {
        return serviceYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.serviceYears
     *
     * @param serviceYears the value for as_keywords.serviceYears
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setServiceYears(Integer serviceYears) {
        this.serviceYears = serviceYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.openApp
     *
     * @return the value of as_keywords.openApp
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Integer getOpenApp() {
        return openApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.openApp
     *
     * @param openApp the value for as_keywords.openApp
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setOpenApp(Integer openApp) {
        this.openApp = openApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.appUserName
     *
     * @return the value of as_keywords.appUserName
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public String getAppUserName() {
        return appUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.appUserName
     *
     * @param appUserName the value for as_keywords.appUserName
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setAppUserName(String appUserName) {
        this.appUserName = appUserName == null ? null : appUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.appPassword
     *
     * @return the value of as_keywords.appPassword
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public String getAppPassword() {
        return appPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.appPassword
     *
     * @param appPassword the value for as_keywords.appPassword
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setAppPassword(String appPassword) {
        this.appPassword = appPassword == null ? null : appPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.loginUrl
     *
     * @return the value of as_keywords.loginUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public String getLoginUrl() {
        return loginUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.loginUrl
     *
     * @param loginUrl the value for as_keywords.loginUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setLoginUrl(String loginUrl) {
        this.loginUrl = loginUrl == null ? null : loginUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.iosDownloadUrl
     *
     * @return the value of as_keywords.iosDownloadUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public String getIosDownloadUrl() {
        return iosDownloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.iosDownloadUrl
     *
     * @param iosDownloadUrl the value for as_keywords.iosDownloadUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setIosDownloadUrl(String iosDownloadUrl) {
        this.iosDownloadUrl = iosDownloadUrl == null ? null : iosDownloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.androidDownloadUrl
     *
     * @return the value of as_keywords.androidDownloadUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public String getAndroidDownloadUrl() {
        return androidDownloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.androidDownloadUrl
     *
     * @param androidDownloadUrl the value for as_keywords.androidDownloadUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setAndroidDownloadUrl(String androidDownloadUrl) {
        this.androidDownloadUrl = androidDownloadUrl == null ? null : androidDownloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.codeIosUrl
     *
     * @return the value of as_keywords.codeIosUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public String getCodeIosUrl() {
        return codeIosUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.codeIosUrl
     *
     * @param codeIosUrl the value for as_keywords.codeIosUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setCodeIosUrl(String codeIosUrl) {
        this.codeIosUrl = codeIosUrl == null ? null : codeIosUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.codeAndroidUrl
     *
     * @return the value of as_keywords.codeAndroidUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public String getCodeAndroidUrl() {
        return codeAndroidUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.codeAndroidUrl
     *
     * @param codeAndroidUrl the value for as_keywords.codeAndroidUrl
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setCodeAndroidUrl(String codeAndroidUrl) {
        this.codeAndroidUrl = codeAndroidUrl == null ? null : codeAndroidUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.preRegdatetime
     *
     * @return the value of as_keywords.preRegdatetime
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Date getPreRegdatetime() {
        return preRegdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.preRegdatetime
     *
     * @param preRegdatetime the value for as_keywords.preRegdatetime
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setPreRegdatetime(Date preRegdatetime) {
        this.preRegdatetime = preRegdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.preRegPassdatetime
     *
     * @return the value of as_keywords.preRegPassdatetime
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Date getPreRegPassdatetime() {
        return preRegPassdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.preRegPassdatetime
     *
     * @param preRegPassdatetime the value for as_keywords.preRegPassdatetime
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setPreRegPassdatetime(Date preRegPassdatetime) {
        this.preRegPassdatetime = preRegPassdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.regdatetime
     *
     * @return the value of as_keywords.regdatetime
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Date getRegdatetime() {
        return regdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.regdatetime
     *
     * @param regdatetime the value for as_keywords.regdatetime
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setRegdatetime(Date regdatetime) {
        this.regdatetime = regdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.regPassdatetime
     *
     * @return the value of as_keywords.regPassdatetime
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Date getRegPassdatetime() {
        return regPassdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.regPassdatetime
     *
     * @param regPassdatetime the value for as_keywords.regPassdatetime
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setRegPassdatetime(Date regPassdatetime) {
        this.regPassdatetime = regPassdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.isPass
     *
     * @return the value of as_keywords.isPass
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Integer getIsPass() {
        return isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.isPass
     *
     * @param isPass the value for as_keywords.isPass
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setIsPass(Integer isPass) {
        this.isPass = isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.checkStatus
     *
     * @return the value of as_keywords.checkStatus
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Integer getCheckStatus() {
        return checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.checkStatus
     *
     * @param checkStatus the value for as_keywords.checkStatus
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setCheckStatus(Integer checkStatus) {
        this.checkStatus = checkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_keywords.isUse
     *
     * @return the value of as_keywords.isUse
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public Integer getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_keywords.isUse
     *
     * @param isUse the value for as_keywords.isUse
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    public void setIsUse(Integer isUse) {
        this.isUse = isUse;
    }

    public AsCustoms getCustoms() {
        return customs;
    }

    public void setCustoms(AsCustoms customs) {
        this.customs = customs;
    }

    public AsSystemconfig getSystemconfig() {
        return systemconfig;
    }

    public void setSystemconfig(AsSystemconfig systemconfig) {
        this.systemconfig = systemconfig;
    }
}