package com.moha.demo.entity;

import java.util.Date;

public class AsLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_logs.id
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_logs.userId
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_logs.userName
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_logs.operateInfo
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    private String operateInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_logs.operatedatetime
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    private Date operatedatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_logs.id
     *
     * @return the value of as_logs.id
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_logs.id
     *
     * @param id the value for as_logs.id
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_logs.userId
     *
     * @return the value of as_logs.userId
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_logs.userId
     *
     * @param userId the value for as_logs.userId
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_logs.userName
     *
     * @return the value of as_logs.userName
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_logs.userName
     *
     * @param userName the value for as_logs.userName
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_logs.operateInfo
     *
     * @return the value of as_logs.operateInfo
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    public String getOperateInfo() {
        return operateInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_logs.operateInfo
     *
     * @param operateInfo the value for as_logs.operateInfo
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    public void setOperateInfo(String operateInfo) {
        this.operateInfo = operateInfo == null ? null : operateInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_logs.operatedatetime
     *
     * @return the value of as_logs.operatedatetime
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    public Date getOperatedatetime() {
        return operatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_logs.operatedatetime
     *
     * @param operatedatetime the value for as_logs.operatedatetime
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    public void setOperatedatetime(Date operatedatetime) {
        this.operatedatetime = operatedatetime;
    }
}