package com.moha.demo.entity;

import java.util.Date;

public class AsRolePremission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.id
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.roleId
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.functionId
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    private Integer functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.creationTime
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    private Date creationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.createdBy
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.lastUpdatetime
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    private Date lastUpdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_role_premission.isStart
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    private Integer isStart;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.id
     *
     * @return the value of as_role_premission.id
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.id
     *
     * @param id the value for as_role_premission.id
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.roleId
     *
     * @return the value of as_role_premission.roleId
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.roleId
     *
     * @param roleId the value for as_role_premission.roleId
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.functionId
     *
     * @return the value of as_role_premission.functionId
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public Integer getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.functionId
     *
     * @param functionId the value for as_role_premission.functionId
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.creationTime
     *
     * @return the value of as_role_premission.creationTime
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.creationTime
     *
     * @param creationTime the value for as_role_premission.creationTime
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.createdBy
     *
     * @return the value of as_role_premission.createdBy
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.createdBy
     *
     * @param createdBy the value for as_role_premission.createdBy
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.lastUpdatetime
     *
     * @return the value of as_role_premission.lastUpdatetime
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public Date getLastUpdatetime() {
        return lastUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.lastUpdatetime
     *
     * @param lastUpdatetime the value for as_role_premission.lastUpdatetime
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public void setLastUpdatetime(Date lastUpdatetime) {
        this.lastUpdatetime = lastUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_role_premission.isStart
     *
     * @return the value of as_role_premission.isStart
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public Integer getIsStart() {
        return isStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_role_premission.isStart
     *
     * @param isStart the value for as_role_premission.isStart
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    public void setIsStart(Integer isStart) {
        this.isStart = isStart;
    }
}