package com.moha.demo.entity;

public class AsSystemconfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_systemconfig.id
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_systemconfig.configType
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    private Integer configType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_systemconfig.configTypeName
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    private String configTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_systemconfig.configTypeValue
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    private Integer configTypeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_systemconfig.configValue
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_systemconfig.isStart
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    private Integer isStart;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_systemconfig.id
     *
     * @return the value of as_systemconfig.id
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_systemconfig.id
     *
     * @param id the value for as_systemconfig.id
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_systemconfig.configType
     *
     * @return the value of as_systemconfig.configType
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    public Integer getConfigType() {
        return configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_systemconfig.configType
     *
     * @param configType the value for as_systemconfig.configType
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    public void setConfigType(Integer configType) {
        this.configType = configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_systemconfig.configTypeName
     *
     * @return the value of as_systemconfig.configTypeName
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    public String getConfigTypeName() {
        return configTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_systemconfig.configTypeName
     *
     * @param configTypeName the value for as_systemconfig.configTypeName
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    public void setConfigTypeName(String configTypeName) {
        this.configTypeName = configTypeName == null ? null : configTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_systemconfig.configTypeValue
     *
     * @return the value of as_systemconfig.configTypeValue
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    public Integer getConfigTypeValue() {
        return configTypeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_systemconfig.configTypeValue
     *
     * @param configTypeValue the value for as_systemconfig.configTypeValue
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    public void setConfigTypeValue(Integer configTypeValue) {
        this.configTypeValue = configTypeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_systemconfig.configValue
     *
     * @return the value of as_systemconfig.configValue
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_systemconfig.configValue
     *
     * @param configValue the value for as_systemconfig.configValue
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_systemconfig.isStart
     *
     * @return the value of as_systemconfig.isStart
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    public Integer getIsStart() {
        return isStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_systemconfig.isStart
     *
     * @param isStart the value for as_systemconfig.isStart
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    public void setIsStart(Integer isStart) {
        this.isStart = isStart;
    }
}