package com.moha.demo.entity;

import java.util.Date;

public class AsUser {
    private AsRole role;
    private AsAccount account;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_user.id
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_user.userCode
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_user.userName
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_user.userPassword
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_user.creationTime
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    private Date creationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_user.lastLoginTime
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_user.createdBy
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_user.lastUpdateTime
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_user.isStart
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    private Integer isStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_user.roleid
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column as_user.salt
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_user.id
     *
     * @return the value of as_user.id
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_user.id
     *
     * @param id the value for as_user.id
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_user.userCode
     *
     * @return the value of as_user.userCode
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_user.userCode
     *
     * @param userCode the value for as_user.userCode
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_user.userName
     *
     * @return the value of as_user.userName
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_user.userName
     *
     * @param userName the value for as_user.userName
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_user.userPassword
     *
     * @return the value of as_user.userPassword
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_user.userPassword
     *
     * @param userPassword the value for as_user.userPassword
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_user.creationTime
     *
     * @return the value of as_user.creationTime
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_user.creationTime
     *
     * @param creationTime the value for as_user.creationTime
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_user.lastLoginTime
     *
     * @return the value of as_user.lastLoginTime
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_user.lastLoginTime
     *
     * @param lastLoginTime the value for as_user.lastLoginTime
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_user.createdBy
     *
     * @return the value of as_user.createdBy
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_user.createdBy
     *
     * @param createdBy the value for as_user.createdBy
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_user.lastUpdateTime
     *
     * @return the value of as_user.lastUpdateTime
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_user.lastUpdateTime
     *
     * @param lastUpdateTime the value for as_user.lastUpdateTime
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_user.isStart
     *
     * @return the value of as_user.isStart
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public Integer getIsStart() {
        return isStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_user.isStart
     *
     * @param isStart the value for as_user.isStart
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public void setIsStart(Integer isStart) {
        this.isStart = isStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_user.roleid
     *
     * @return the value of as_user.roleid
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_user.roleid
     *
     * @param roleid the value for as_user.roleid
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column as_user.salt
     *
     * @return the value of as_user.salt
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column as_user.salt
     *
     * @param salt the value for as_user.salt
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    public AsRole getRole() {
        return role;
    }

    public void setRole(AsRole role) {
        this.role = role;
    }

    public AsAccount getAccount() {
        return account;
    }

    public void setAccount(AsAccount account) {
        this.account = account;
    }
}