package com.moha.demo.entity;

public class HatArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_area.id
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_area.areaID
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    private Integer areaID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_area.area
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_area.father
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    private Integer father;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_area.id
     *
     * @return the value of hat_area.id
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_area.id
     *
     * @param id the value for hat_area.id
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_area.areaID
     *
     * @return the value of hat_area.areaID
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    public Integer getAreaID() {
        return areaID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_area.areaID
     *
     * @param areaID the value for hat_area.areaID
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    public void setAreaID(Integer areaID) {
        this.areaID = areaID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_area.area
     *
     * @return the value of hat_area.area
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_area.area
     *
     * @param area the value for hat_area.area
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_area.father
     *
     * @return the value of hat_area.father
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    public Integer getFather() {
        return father;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_area.father
     *
     * @param father the value for hat_area.father
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    public void setFather(Integer father) {
        this.father = father;
    }
}