package com.moha.demo.entity;

public class HatCity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_city.id
     *
     * @mbggenerated Mon Feb 05 15:13:41 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_city.cityID
     *
     * @mbggenerated Mon Feb 05 15:13:41 CST 2018
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_city.city
     *
     * @mbggenerated Mon Feb 05 15:13:41 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_city.father
     *
     * @mbggenerated Mon Feb 05 15:13:41 CST 2018
     */
    private Integer father;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_city.id
     *
     * @return the value of hat_city.id
     *
     * @mbggenerated Mon Feb 05 15:13:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_city.id
     *
     * @param id the value for hat_city.id
     *
     * @mbggenerated Mon Feb 05 15:13:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_city.cityID
     *
     * @return the value of hat_city.cityID
     *
     * @mbggenerated Mon Feb 05 15:13:41 CST 2018
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_city.cityID
     *
     * @param cityid the value for hat_city.cityID
     *
     * @mbggenerated Mon Feb 05 15:13:41 CST 2018
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_city.city
     *
     * @return the value of hat_city.city
     *
     * @mbggenerated Mon Feb 05 15:13:41 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_city.city
     *
     * @param city the value for hat_city.city
     *
     * @mbggenerated Mon Feb 05 15:13:41 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_city.father
     *
     * @return the value of hat_city.father
     *
     * @mbggenerated Mon Feb 05 15:13:41 CST 2018
     */
    public Integer getFather() {
        return father;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_city.father
     *
     * @param father the value for hat_city.father
     *
     * @mbggenerated Mon Feb 05 15:13:41 CST 2018
     */
    public void setFather(Integer father) {
        this.father = father;
    }
}