package com.moha.demo.entity;

public class HatProvince {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_province.id
     *
     * @mbggenerated Mon Feb 05 14:41:38 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_province.provinceID
     *
     * @mbggenerated Mon Feb 05 14:41:38 CST 2018
     */
    private Integer provinceID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_province.province
     *
     * @mbggenerated Mon Feb 05 14:41:38 CST 2018
     */
    private String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_province.id
     *
     * @return the value of hat_province.id
     *
     * @mbggenerated Mon Feb 05 14:41:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_province.id
     *
     * @param id the value for hat_province.id
     *
     * @mbggenerated Mon Feb 05 14:41:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_province.provinceID
     *
     * @return the value of hat_province.provinceID
     *
     * @mbggenerated Mon Feb 05 14:41:38 CST 2018
     */
    public Integer getProvinceID() {
        return provinceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_province.provinceID
     *
     * @param provinceID the value for hat_province.provinceID
     *
     * @mbggenerated Mon Feb 05 14:41:38 CST 2018
     */
    public void setProvinceID(Integer provinceID) {
        this.provinceID = provinceID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_province.province
     *
     * @return the value of hat_province.province
     *
     * @mbggenerated Mon Feb 05 14:41:38 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_province.province
     *
     * @param province the value for hat_province.province
     *
     * @mbggenerated Mon Feb 05 14:41:38 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }
}