package com.moha.demo.dao;

import com.moha.demo.entity.AsAccount;
import org.apache.ibatis.annotations.Param;

public interface AsAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_account
     *
     * @mbggenerated Mon Feb 05 14:30:22 CST 2018
     */
    AsAccount selectByPrimaryKey(Integer id);

    //根据用户id得到账户
    AsAccount getAccount(@Param("id") int id);
    //根据用户id修改账户金额
    void modifyAccount(@Param("userid") int userid, @Param("money") Double money);
    //根据用户id添加账户
    void addAccount(@Param("userid") int userid, @Param("money") Double money);
}