package com.moha.demo.dao;

import com.moha.demo.entity.AsAccountdetail;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface AsAccountdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_accountdetail
     *
     * @mbggenerated Mon Feb 05 14:40:35 CST 2018
     */
    AsAccountdetail selectByPrimaryKey(Integer id);

    //根据用户id得到账户详细表并分页
     List<AsAccountdetail> showDetail(@Param("id")int id,
                                          @Param("lineNum")int lineNum,
                                          @Param("pageSize")int pageSize,
                                          @Param("detailType")int detailType,
                                          @Param("start")Date starttime,
                                          @Param("end")Date endtime);
    //得到总记录数
     int detailCount(@Param("id")int id,
                           @Param("detailType")int detailType,
                           @Param("start")Date starttime,
                           @Param("end")Date endtime);

    //预付款流水报表
     List<AsAccountdetail> preRunning(@Param("start")Date starttime,
                                          @Param("end")Date endtime);

    //代理商流水报表
     List<AsAccountdetail> agentRunning(@Param("start")Date starttime,
                                            @Param("end")Date end);

    //添加详细账单
     void addDetail(AsAccountdetail accountdetail);
}