package com.moha.demo.dao;

import com.moha.demo.entity.AsCustoms;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AsCustomsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_customs
     *
     * @mbggenerated Mon Feb 05 14:40:49 CST 2018
     */
    AsCustoms selectByPrimaryKey(Integer id);

    //模糊分页查询客户
     List<AsCustoms> likefind(@Param("lineNum")Integer lineNum, @Param("pageSize")Integer pageSize, @Param("name")String name);
    //模糊查询数据行数
     int count(@Param("name")String name);
    //根据姓名模糊查询客户
     List<AsCustoms> likeCus(@Param("name")String name);
    //客户添加
     void addCus(AsCustoms customs);

    //客户修改
     void modifyCus(AsCustoms customs);

    //根据客户主键ID显示查客户信息
     AsCustoms findone(Integer id);

    //根据客户主键ID开启或关闭客户状态
     void state(@Param("id")Integer id,@Param("customStatus")Integer customStatus);
}