package com.moha.demo.dao;

import com.moha.demo.entity.AsKeywords;
import com.moha.demo.model.ProductCount;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AsKeywordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_keywords
     *
     * @mbggenerated Mon Feb 05 14:40:59 CST 2018
     */
    AsKeywords selectByPrimaryKey(Integer id);

    //门户管理模糊查询分页显示
     List<AsKeywords> getportal(@Param("id")int id,
                                    @Param("lineNum")int lineNum,
                                    @Param("pageSize")int pageSize,
                                    @Param("keywordName")String keywordName,
                                    @Param("customName")String customName);
    //查询总记录数
     int getCount(@Param("id")int id,
                        @Param("keywordName")String keywordName,
                        @Param("customName")String customName);

    //查看门户
     AsKeywords portalView(@Param("id")int id);

    //修改门户
     void portalUpdate(@Param("appUserName")String appUserName,
                             @Param("appPassword")String appPassword,
                             @Param("iosDownloadUrl")String iosDownloadUrl,
                             @Param("codeIosUrl")String codeIosUrl,
                             @Param("androidDownloadUrl")String androidDownloadUrl,
                             @Param("codeAndroidUrl")String codeAndroidUrl,
                             @Param("kid")int kid);
    //查询是否存在关键词
     int keyCount(String keywords);
    //添加关键词
     void addKeyWord(@Param("keywords")AsKeywords keywords);

    //获取关键词表分页
     List<AsKeywords> getKeywords(@Param("lineNum")int lineNum,
                                      @Param("pageSize")int pageSize,
                                      @Param("keywordName")String keywordName);
    //总记录数
     int keywordsCount(@Param("keywordName")String keywordName);

    //根据keyname获取关键词信息
     AsKeywords showKey(@Param("keyname")String keyname);

    //开通app
     void openApp(@Param("appPassword")String appPassword,
                        @Param("appUserName")String appUserName,
                        @Param("kid")int kid);
    //关键词续费
     void renew(@Param("years")int years,
                      @Param("kid")int kid);

    //修改审核状态
     void updateStatus(@Param("status")int status,
                             @Param("keyname")String keyname);
    //修改使用状态
     void updateUse(@Param("isUse")int isUse,
                          @Param("keyname")String keyname);
    List<AsKeywords> allkeys();

    //产品分类数量/金额汇总
     List<ProductCount> getCountType();
}