package com.moha.demo.dao;

import com.moha.demo.entity.AsLogs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AsLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_logs
     *
     * @mbggenerated Mon Feb 05 14:41:04 CST 2018
     */
    AsLogs selectByPrimaryKey(Integer id);

    //添加日志操作
     void addlogs(AsLogs logs);
    //返回日志集合
     List<AsLogs> logs(@Param("lineNum")Integer lineNum, @Param("pageSize")Integer pageSize);
    //返回数据行数
     int logsline();

    List<AsLogs> allLogs();
}