package com.moha.demo.dao;

import com.moha.demo.entity.AsRolePremission;

import java.util.List;

public interface AsRolePremissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_role_premission
     *
     * @mbggenerated Mon Feb 05 14:41:14 CST 2018
     */
    AsRolePremission selectByPrimaryKey(Integer id);

    //增加权限
     void addPremission(AsRolePremission role_premission);

    //删除权限
     void delPremission(Integer roleId);

    //查询单个角色的权限功能ID集合
     List<Integer> role_premissions(Integer roleId);
}