package com.moha.demo.dao;

import com.moha.demo.entity.AsSystemconfig;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AsSystemconfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_systemconfig
     *
     * @mbggenerated Mon Feb 05 14:41:19 CST 2018
     */
    AsSystemconfig selectByPrimaryKey(Integer id);

    //查询财务类型
     List<AsSystemconfig> systemconfigs();

    //类型
     List<AsSystemconfig> type(@Param("configType")Integer configType, @Param("isStart")Integer isStart);

    // 增加系统配置
     void addSystemconfig(AsSystemconfig systemconfig);

    //分页查询
     List<AsSystemconfig> pagefind(@Param("lineNum")Integer lineNum,@Param("pageSize")Integer pageSize,@Param("configType") Integer configType);

    //模糊查询系统配置数据行数
     int count(@Param("configType") Integer configType);

    //删除系统配置
     void delete(@Param("id") Integer id);

    //根据 configType查询类集合
     List<AsSystemconfig> getConfig(@Param("configType") int configType);

    //动态查询
     AsSystemconfig findsys(AsSystemconfig systemconfig);

    //更新配置
      void update(AsSystemconfig systemconfig);

    //根据ID查询配置
     AsSystemconfig findByID(@Param("id") Integer id);
}