package com.moha.demo.dao;

import com.moha.demo.entity.AsUser;
import com.moha.demo.model.BalanceView;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table as_user
     *
     * @mbggenerated Mon Feb 05 14:41:23 CST 2018
     */
    AsUser selectByPrimaryKey(Integer id);

    // 分页查询所有用户
     List<AsUser> userlist(@Param("lineNum") Integer lineNum, @Param("pageSize") Integer pageSize,
                               @Param("userName") String userName, @Param("roleid") Integer roleid, @Param("isStart") Integer isStart);

    // 模糊查询用户数量
     int num(@Param("userName") String userName, @Param("roleid") Integer roleid,
                   @Param("isStart") Integer isStart);

    // 增加用户
     void addUser(AsUser user);

    //修改用户
     void modifyUser(AsUser user);

    // 删除用户
     void delUser(Integer id);

    // 根据用户姓名 用户身份 用户是否启用，模糊查询
     List<AsUser> findUsers(@Param("userName") String userName, @Param("roleid") Integer roleid,
                                @Param("isStart") Integer isStart);
    // 查询用户
     AsUser user(@Param("id") int id);

    //登录
    AsUser login(@Param("usercode")String usercode,@Param("password")String password);

    //修改密码
    void pModify(@Param("id")int id,@Param("newpwd")String newpwd,@Param("salt")String salt);

    //修改上次登录时间
    void lastLogin(@Param("id")int id);

    //代理商余额报表
    List<BalanceView> balance();
    //
    AsUser selectUserByusercode(String usercode);
}