package com.moha.demo.dao;

import com.moha.demo.entity.Demo;

public interface DemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbggenerated Tue Apr 18 11:29:06 CST 2017
     */
    Demo selectByPrimaryKey(Integer id);
}