package com.moha.demo.dao;

import com.moha.demo.entity.HatArea;

import java.util.List;

public interface HatAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbggenerated Mon Feb 05 14:41:29 CST 2018
     */
    HatArea selectByPrimaryKey(Integer id);

    //根据cityID查询区
     List<HatArea> areas(String cityID);
}