package com.moha.demo.dao;

import com.moha.demo.entity.HatProvince;

import java.util.List;

public interface HatProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbggenerated Mon Feb 05 14:41:38 CST 2018
     */
    HatProvince selectByPrimaryKey(Integer id);

    //省查询
     List<HatProvince> provinces();

    //省查询根据provinceId查询省
     HatProvince pro(String provinceId);
}